# Generated by Django 4.0.6 on 2022-07-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradesA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('calc', models.FloatField()),
                ('oop', models.FloatField()),
                ('dld', models.FloatField()),
                ('istd', models.FloatField()),
                ('imgt', models.FloatField()),
                ('ap', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GradesB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('calc', models.FloatField()),
                ('oop', models.FloatField()),
                ('dld', models.FloatField()),
                ('istd', models.FloatField()),
                ('imgt', models.FloatField()),
                ('ap', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GradesC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('calc', models.FloatField()),
                ('oop', models.FloatField()),
                ('dld', models.FloatField()),
                ('istd', models.FloatField()),
                ('imgt', models.FloatField()),
                ('ap', models.FloatField()),
            ],
        ),
    ]
